version: 2
jobs:
  linter:
    docker:
      - image: 'circleci/node:10'
    steps:
      - checkout
      - restore_cache:
          key: 'podtema-v1-{{ checksum "package-lock.json" }}'
      - run:
          name: Install dependencies
          command: npm install
      - save_cache:
          key: 'podtema-v1-{{ checksum "package-lock.json" }}'
          paths:
            - ./node_modules
      - run:
          name: Prettier
          command: ./node_modules/.bin/prettier --semi=true --single-quote=true --trailing-comma=es5 --check './src/**/*.{js,jsx,ts,tsx}'

workflows:
  version: 2
  tests:
    jobs:
      - linter:
          filters:
            branches:
              ignore: master
